apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff-deployment
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-bff
  template:
    metadata:
      labels:
        app: web-bff
    spec:
      containers:
      - name: web-bff
        image: ybhartia/web-bff:v1
        imagePullPolicy : Always
        ports:
        - containerPort: 80
        env:
        - name: CUSTOMER_SERVICE_URL
          value: "http://customer-service:3000"
        - name: BOOK_SERVICE_URL
          value: "http://book-service:3000"
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5