# Use Node.js Alpine image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json from the books-service directory
COPY customer-service/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code from the books-service directory
COPY customer-service/ .

# Expose port 3000
EXPOSE 3000

# Start the service
CMD ["node", "customer-service.js"]
